### ISSUE TITLE
Уникальность атрибута id

### ISSUE THREAD

**Issue by vladimirfriptu** [Gulfakse/learnhtml#3]
https://github.com/Gulfakse/learnhtml/blob/13e8a2432ec7aae7b9dba077594c7e71c93c7f92/index.html#L53

атрибут id является уникальным и на одной странице не может находится несколько id с одинаковым значением

**Comment by Gulfakse** [comment]
исправила

**Comment by goiteensvfriptu** [comment]
Не могу закрыть issue, надо будет с тобой глянуть настройки что бы дать мне доступ на закрытие issues )
