### ISSUE TITLE
Не корректное использования атрибута alt на теге img

### ISSUE THREAD

**Issue by vladimirfriptu** [Gulfakse/learnhtml#4]
https://github.com/Gulfakse/learnhtml/blob/57818fc5df993afe03a6c1bb2ce7f2e41e19665b/hw.html#L88

⚠️  Атрибут alt должен описывать что нарисовано на картинке

👉  **Документация** - https://developer.mozilla.org/ru/docs/Web/HTML/Element/img#alt

**Comment by Gulfakse** [comment]
пофиксила
