### ISSUE TITLE
Форматирование кода

### ISSUE THREAD

**Issue by vladimirfriptu** [Gulfakse/learnhtml#5]
🌮  На боевых проектах всегда используется автоматическкое форматирование кода, которое позволяет прийти к универсальному стилю написание для всех разработчиков в команде.

👍  Тебе пока достаточно почитать о форматировании кода встроенными плангинами VSCode

👉  https://codeahoy.com/q/q508/vscode-format-source#:~:text=You%20can%20easily%20format%20your,Ubuntu%3A%20Ctrl%20%2B%20Shift%20%2B%20I

🏁  Также стоит пробежаться по официальной документации "как использовать VSCode эффективно" - https://code.visualstudio.com/docs/editor/codebasics
👉 Тут главное понять какие есть возможности быстрого редактирования кода и ускорение своей работы (поиска, рефакторинга, переименования и тд)

**Comment by Gulfakse** [comment]
я кст еще знаю комбинацию ctri+shift+p (винда)
эта комбинация помогает быстрее теги писать чет такое,я принцип работы смогу показать в мите,если непонятно
с инфой ознакомлюссь
