### ISSUE TITLE
Замечания к learnhtml/doctype.html

### ISSUE THREAD

**Issue by goiteensvfriptu** [Gulfakse/learnhtml#6]
Замечания

https://github.com/Gulfakse/learnhtml/blob/48c880b8245d60296b93afa547f5eed98cbad370/doctype.html#L44-L48

тут не нужен `display: flex`

<hr />

https://github.com/Gulfakse/learnhtml/blob/48c880b8245d60296b93afa547f5eed98cbad370/doctype.html#L49-L52

тут `height: auto` тоже не нужен так как он и так по умолчанию будет auto

<hr />

❤️  Очень хорошая работа! Особенно понравилось как поиспользовала псевдо классы и псевдо элементы! Умничка

**Comment by Gulfakse** [comment]
спасибо,все исправила
